USE user;

CREATE TABLE IF NOT EXISTS members(
	id VARCHAR(50) PRIMARY KEY,
	pwd VARCHAR(255) NOT NULL,
	name VARCHAR(50) NOT NULL,
	birthday DATE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	score VARCHAR(255)
	)